### PR TITLE
Weather database

### LINKED ISSUE #7: Add bookmarking functionality
Create a database to store climate, POI and YouTube video data. Add functions to add bookmarks, show a list of bookmarks, and show individual bookmark data.

### PR DESCRIPTION
**Pull request by Albaito**
Finally think the branch is ready to merge to main, still need to do some exception handling, but it should work as needed. @ji4814yx @kpalmateer @aloubrehima Thoughts?

### CODE REVIEW

**Comment by kpalmateer** [comment]
@Albaito Did you mean to delete the geocode_api.py file? If not, could you re-add it and re-commit?

Other than that, I'm good with merging this.

**Comment by Albaito** [comment]
@kpalmateer I did not mean to delete that, I'll re-add and commit shortly.

**Comment by Albaito** [comment]
@kpalmateer ok, so the version of api_requests I had was pulled from when you hadn't finished the geocode_api so I just removed altogether from this branch.

**Comment by kpalmateer** [comment]
Everything looks good! The only existing merge conflict was with the .gitignore file and it was easy to resolve. I pulled the code and I think it's ready for merge.

**Pull request merged**
